# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgsLayerParser
                                 A QGIS plugin
 Parse QGIS 3 project files and write a JSON config file with layer information.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-05
        copyright            : (C) 2022 by Gerald Kogler/PSIG
        email                : geraldo@servus.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import os
import site
site.addsitedir(os.path.abspath(os.path.dirname(__file__) + '/libs'))

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QgsLayerParser class from file QgsLayerParser.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgs_layer_parser import QgsLayerParser
    return QgsLayerParser(iface)
