# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerTree2JSON
                                 A QGIS plugin
 Parse QGIS 3 project and write a JSON config file with layer information.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-09
        copyright            : (C) 2022 by Gerald Kogler / PSIG
        email                : geraldo@servus.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

#import os
#import site
#site.addsitedir(os.path.abspath(os.path.dirname(__file__) + '/libs'))

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayerTree2JSON class from file LayerTree2JSON.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .layertree2json import LayerTree2JSON
    return LayerTree2JSON(iface)
